# Generated by Django 5.1.3 on 2024-11-17 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(max_length=140)),
                ('full_description', models.TextField(max_length=1000)),
                ('passcode', models.CharField(max_length=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('short_bio', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.TimeField()),
                ('finishing_time', models.TimeField(blank=True, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('activities', models.ManyToManyField(to='appdata.activity')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.area')),
                ('players', models.ManyToManyField(to='appdata.user')),
            ],
        ),
        migrations.CreateModel(
            name='GameActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.activity')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.game')),
            ],
        ),
        migrations.CreateModel(
            name='TeamUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appdata.user')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='member',
            field=models.ManyToManyField(related_name='member', to='appdata.user'),
        ),
        migrations.AddField(
            model_name='team',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to='appdata.user'),
        ),
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.game')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appdata.user')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=32)),
                ('venue_opening_hour', models.TimeField(blank=True, null=True)),
                ('venue_closing_hour', models.TimeField(blank=True, null=True)),
                ('description_of_the_venue', models.TextField(max_length=200)),
                ('venue_link_tripadvisor', models.URLField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.area')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.venue'),
        ),
    ]
