# Generated by Django 5.1.3 on 2024-11-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameuser',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teamuser',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamuser',
            name='user',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='area_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='member',
            new_name='team_user',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='venue_closing_hour',
            new_name='closing_hour',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='description_of_the_venue',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='venue_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='venue_opening_hour',
            new_name='opening_hour',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='venue_link_tripadvisor',
        ),
        migrations.AddField(
            model_name='area',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='tripadvisor_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='short_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='starting_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='GameActivity',
        ),
        migrations.DeleteModel(
            name='GameUser',
        ),
        migrations.DeleteModel(
            name='TeamUser',
        ),
    ]
