# Generated by Django 5.1.3 on 2024-11-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0002_alter_game_starting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='picture',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userpic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='venue',
            name='picture',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
