# Generated by Django 5.1.3 on 2024-11-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0003_area_picture_customuser_userpic_venue_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userpic',
            field=models.ImageField(default='default_user_picture.jpg', upload_to='profile_pictures'),
        ),
    ]
