# Generated by Django 5.1.3 on 2024-11-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0004_alter_customuser_userpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userpic',
            field=models.ImageField(default='default_userpic.png', upload_to='profile_pictures'),
        ),
    ]
