# Generated by Django 5.1.3 on 2024-11-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0005_alter_customuser_userpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='short_description',
            field=models.TextField(max_length=80),
        ),
    ]
