# Generated by Django 5.1.3 on 2024-11-25 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0006_alter_activity_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appdata.area'),
        ),
        migrations.AlterField(
            model_name='game',
            name='starting_time',
            field=models.TimeField(),
        ),
    ]
