# Generated by Django 5.1.3 on 2024-11-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0007_customuser_current_area_alter_game_starting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='closing_hour',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='opening_hour',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
