# Generated by Django 5.1.3 on 2024-11-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0008_alter_venue_closing_hour_alter_venue_opening_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='finishing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='starting_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='closing_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='opening_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
