# Generated by Django 5.1.3 on 2024-11-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0009_alter_game_finishing_time_alter_game_starting_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='picture',
            field=models.ImageField(null=True, upload_to='venue_pictures'),
        ),
    ]
