# Generated by Django 5.1.3 on 2024-11-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0011_game_teams_alter_game_starting_time_activitycheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='weather_id',
            field=models.CharField(default='588409', max_length=10),
        ),
    ]
