# Generated by Django 5.1.3 on 2024-11-29 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0012_area_weather_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userpic',
            field=models.ImageField(blank=True, default='default_userpic.png', null=True, upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_user',
            field=models.ManyToManyField(blank=True, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venue',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='venue_pictures'),
        ),
    ]
