# Generated by Django 5.1.3 on 2024-11-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0013_alter_area_picture_alter_customuser_userpic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/area_pictures'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userpic',
            field=models.ImageField(blank=True, default='static/images/default_userpic.png', null=True, upload_to='static/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/venue_pictures'),
        ),
    ]
